# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  gradle-artifactory:
    type: maven-repository
    url: https://octofelickz.jfrog.io/artifactory/gradle-registry
    username: felickz
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
updates:
  # ---------- GitHub Actions ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "felickz"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  # ---------- Maven  ----------
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    reviewers:
      - "felickz"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: version-updates # Applies the group rule to version updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
                      # ecosystem. Note: using "*" may open a large pull request
        # Define patterns to exclude dependencies from the group (based on
        # dependency name)
        exclude-patterns:
          - "org.testcontainers:jdbc"
        update-types:
        - "minor"
        - "patch"
      development-dependencies:
        dependency-type: "development"
